### ISSUE TITLE
make a script that will install apps on first boot

### ISSUE THREAD

**Issue by ANDROID2468** [ANDROID2468/fire-os-revamped-5th-7th-gen#14]
making a script that will install apps on first boot. there is not a lot of space on the system partition so this will just install them like normal apps.

**Comment by ghost** [comment]
That should be pretty easy, just `pm install <apk file>`

**Comment by ANDROID2468** [comment]
> That should be pretty easy, just `pm install <apk file>`

I will be working on this in the upcoming update.

**Comment by ANDROID2468** [comment]
I am not going to do this anymore. I am going to deodex the roms (I successfully did it on the 7th gen) which I ended up with 166MB's after that.
